Fix Github Actions (#111)
*  workflow: rewrite

*  workflow: add changelog for printing changelog

* rename generate-publish-matrix.sh to generate-build-matrix.sh

* add get-modrinth-dependency-url.sh‎ for getting jar url from slug (script from https://github.com/Faboslav/friends-and-foes/blob/master/.github/scripts/get-modrinth-dependency-url.sh)

* added justfile and just to flake.nix

* removed CI things from settings.gradle.kts

* don't build javadoc and sources jars

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,25 +1,86 @@
-# Automatically build the project and run any configured tests for every push
-# and submitted pull request. This can help catch issues that only occur on
-# certain platforms or Java versions, and provides a first line of defense
-# against bad commits.
-
 name: build
-on: [ pull_request, push, workflow_call, workflow_dispatch ]
+
+on:
+    pull_request:
+    push:
+    workflow_dispatch:
+        inputs:
+            mod_loaders:
+                description: "Optional list of mod loaders to build"
+                required: false
+                default: ""
+                type: string
+            versions:
+                description: "Optional list of Minecraft versions to build"
+                required: false
+                default: ""
+                type: string
+            run_tests:
+                description: "Run client/server after build"
+                required: false
+                default: false
+                type: boolean
+    workflow_call:
+        inputs:
+            mod_loaders:
+                description: "Optional list of mod loaders to build"
+                required: false
+                default: ""
+                type: string
+            versions:
+                description: "Optional list of Minecraft versions to build"
+                required: false
+                default: ""
+                type: string
+            run_tests:
+                description: "Run client/server after build"
+                required: false
+                default: false
+                type: boolean
 
 jobs:
-    build:
+    generate-build-matrix:
         runs-on: ubuntu-latest
-        # timeout-minutes: 30
+        name: Generate build matrix
+        outputs:
+            matrix: ${{ steps.set-matrix.outputs.matrix }}
 
         steps:
             -   name: Checkout repository
-                uses: actions/checkout@v5
+                uses: actions/checkout@v6
+
+            -   name: Grant execute permission to generate-build-matrix.sh
+                run: chmod +x ./.github/scripts/generate-build-matrix.sh
+
+            -   name: Generate matrix for the build job
+                id: set-matrix
+                run: ./.github/scripts/generate-build-matrix.sh "${{ inputs.mod_loaders || github.event.inputs.mod_loaders || '' }}" "${{ inputs.versions || github.event.inputs.versions || '' }}"
+
+    build:
+        runs-on: ubuntu-latest
+        needs: generate-build-matrix
+        name: Build ${{ matrix.mod_loader }} ${{ matrix.version }}
+        # timeout-minutes: 30
+        strategy:
+            fail-fast: false
+            matrix: ${{ fromJson(needs.generate-build-matrix.outputs.matrix) }}
+
+        steps:
+            -   name: Checkout repository
+                uses: actions/checkout@v6
+
+            -   name: Grant execute permission to parse-gradle-properties.sh
+                run: chmod +x ./.github/scripts/parse-gradle-properties.sh
+
+            -   name: "Parse gradle properties"
+                id: gradle-properties
+                run: ./.github/scripts/parse-gradle-properties.sh ${{ matrix.version }}
 
             -   name: Set up JDK 21
                 uses: actions/setup-java@v5
                 with:
                     distribution: "temurin"
-                    java-version: 21
+                    java-version: ${{ steps.gradle-properties.outputs.JAVA_VERSION }}
 
             -   name: "Setup gradle"
                 uses: gradle/actions/setup-gradle@v5
@@ -28,27 +89,144 @@ jobs:
                     gradle-version: wrapper
                     add-job-summary: "on-failure"
 
-            -   name: Grant execute permission to parse-gradle-properties.sh
-                run: chmod +x ./.github/scripts/parse-gradle-properties.sh
-
-            -   name: "Parse gradle properties"
-                id: gradle-properties
-                run: ./.github/scripts/parse-gradle-properties.sh
-
             -   name: Grant execute permission to gradlew
                 run: chmod +x gradlew
 
-            -   name: "Run build"
-                run: ./gradlew build --debug --info --stacktrace
+            -   name: "Run build for ${{ matrix.mod_loader }} ${{ matrix.version }}"
+                run: ./gradlew :${{ matrix.mod_loader }}:${{ matrix.version }}:build --info --stacktrace
 
             -   name: "Prepare artifacts"
                 run: |
                     mkdir -p artifacts
-                    find . -path "./*/versions/*/build/libs/*.jar" ! -name "*-common*.jar" -exec cp {} artifacts/ \;
+                    jar_path="./${{ matrix.mod_loader }}/versions/${{ matrix.version }}/build/libs/${{ steps.gradle-properties.outputs.MOD_ID }}-${{ matrix.mod_loader }}-${{ steps.gradle-properties.outputs.MOD_VERSION }}+mc${{ matrix.version }}.jar"
+                    if [[ ! -f "$jar_path" ]]; then
+                        echo "Expected artifact not found: $jar_path"
+                        exit 1
+                    fi
+                    cp "$jar_path" artifacts/
 
             -   name: "Upload artifacts"
-                uses: actions/upload-artifact@v4
+                uses: actions/upload-artifact@v7 # TODO: upload single file without zipping https://github.com/actions/upload-artifact/releases/tag/v7.0.0
                 with:
-                    name: ${{ steps.gradle-properties.outputs.MOD_ID }}-artifacts-${{ steps.gradle-properties.outputs.MOD_VERSION }}
+                    name: ${{ steps.gradle-properties.outputs.MOD_ID }}-${{ matrix.mod_loader }}-${{ matrix.version }}-artifacts-${{ steps.gradle-properties.outputs.MOD_VERSION }}
                     if-no-files-found: error
-                    path: artifacts/*.jar
+                    path: artifacts/${{ steps.gradle-properties.outputs.MOD_ID }}-${{ matrix.mod_loader }}-${{ steps.gradle-properties.outputs.MOD_VERSION }}+mc${{ matrix.version }}.jar
+
+    run-client:
+        runs-on: ubuntu-latest
+        needs: [ build, generate-build-matrix ]
+        if: ${{ inputs.run_tests }}
+        name: Run client ${{ matrix.mod_loader }} ${{ matrix.version }}
+        strategy:
+            fail-fast: false
+            matrix: ${{ fromJson(needs.generate-build-matrix.outputs.matrix) }}
+
+        steps:
+            -   name: Checkout repository
+                uses: actions/checkout@v6
+
+            -   name: Grant execute permission to parse-gradle-properties.sh
+                run: chmod +x ./.github/scripts/parse-gradle-properties.sh
+
+            -   name: Parse gradle properties
+                id: gradle-properties
+                run: ./.github/scripts/parse-gradle-properties.sh ${{ matrix.version }}
+
+            -   name: Set up JDK
+                uses: actions/setup-java@v5
+                with:
+                    distribution: "temurin"
+                    java-version: ${{ steps.gradle-properties.outputs.JAVA_VERSION }}
+
+            -   name: Download build artifact
+                uses: actions/download-artifact@v8
+                with:
+                    name: ${{ steps.gradle-properties.outputs.MOD_ID }}-${{ matrix.mod_loader }}-${{ matrix.version }}-artifacts-${{ steps.gradle-properties.outputs.MOD_VERSION }}
+                    path: artifacts
+
+            -   name: Copy mod jar & test resources to run/
+                run: |
+                    mkdir -p run/mods
+                    cp artifacts/*.jar run/mods/
+
+                    mkdir -p run/saves/wd_PlaygroundVoid/datapacks
+                    mkdir -p run/resourcepacks
+
+                    cp -a test/wd_PlaygroundVoid run/saves/
+                    cp -a test/dp_* run/saves/wd_PlaygroundVoid/datapacks/
+                    cp -a test/rp_* run/resourcepacks/
+
+            -   name: Grant execute permission to get-modrinth-dependency-url.sh
+                run: chmod +x ./.github/scripts/get-modrinth-dependency-url.sh
+
+            -   name: "Download Cloth Config API"
+                run: |
+                    MOD_URL=$(./.github/scripts/get-modrinth-dependency-url.sh "cloth-config" "${{ steps.gradle-properties.outputs.DEPS_CLOTH_CONFIG }}+${{ matrix.mod_loader }}" "${{ matrix.mod_loader }}")
+                    wget -P run/mods "$MOD_URL"
+
+            -   name: Run client runtime test
+                uses: headlesshq/mc-runtime-test@4.1.0
+                with:
+                    mc: ${{ matrix.version }}
+                    modloader: ${{ matrix.mod_loader }}
+                    regex: .*${{ matrix.mod_loader }}.*
+                    mc-runtime-test: ${{ matrix.mod_loader == 'forge' && 'lexforge' || matrix.mod_loader }}
+                    java: ${{ steps.gradle-properties.outputs.JAVA_VERSION }}
+                    headlessmc-command: '--jvm "-Djava.awt.headless=true" --server'
+                    fabric-api: ${{ steps.gradle-properties.outputs.DEPS_FABRIC_API }}
+
+    run-server:
+        runs-on: ubuntu-latest
+        needs: [ build, generate-build-matrix ]
+        if: ${{ inputs.run_tests }}
+        name: Run server ${{ matrix.mod_loader }} ${{ matrix.version }}
+        strategy:
+            fail-fast: false
+            matrix: ${{ fromJson(needs.generate-build-matrix.outputs.matrix) }}
+
+        steps:
+            -   name: Checkout repository
+                uses: actions/checkout@v6
+
+            -   name: Grant execute permission to parse-gradle-properties.sh
+                run: chmod +x ./.github/scripts/parse-gradle-properties.sh
+
+            -   name: Parse gradle properties
+                id: gradle-properties
+                run: ./.github/scripts/parse-gradle-properties.sh ${{ matrix.version }}
+
+            -   name: Set up JDK
+                uses: actions/setup-java@v5
+                with:
+                    distribution: "temurin"
+                    java-version: ${{ steps.gradle-properties.outputs.JAVA_VERSION }}
+
+            -   name: Download build artifact
+                uses: actions/download-artifact@v8
+                with:
+                    name: ${{ steps.gradle-properties.outputs.MOD_ID }}-${{ matrix.mod_loader }}-${{ matrix.version }}-artifacts-${{ steps.gradle-properties.outputs.MOD_VERSION }}
+                    path: artifacts
+
+            -   name: Copy mod jar to run/
+                run: |
+                    mkdir -p run/mods
+                    cp artifacts/*.jar run/mods/
+
+            -   name: Grant execute permission to get-modrinth-dependency-url.sh
+                run: chmod +x ./.github/scripts/get-modrinth-dependency-url.sh
+
+            -   name: "Download Cloth Config API"
+                run: |
+                    MOD_URL=$(./.github/scripts/get-modrinth-dependency-url.sh "cloth-config" "${{ steps.gradle-properties.outputs.DEPS_CLOTH_CONFIG }}+${{ matrix.mod_loader }}" "${{ matrix.mod_loader }}")
+                    wget -P run/mods "$MOD_URL"
+
+            -   name: Run server runtime test
+                uses: headlesshq/mc-runtime-test@4.1.0
+                with:
+                    mc: ${{ matrix.version }}
+                    modloader: ${{ matrix.mod_loader }}
+                    java: ${{ steps.gradle-properties.outputs.JAVA_VERSION }}
+                    regex: .*${{ matrix.mod_loader }}.*
+                    mc-runtime-test: ${{ matrix.mod_loader == 'forge' && 'lexforge' || matrix.mod_loader }}
+                    headlessmc-command: '--jvm "-Djava.awt.headless=true" --server'
+                    fabric-api: ${{ steps.gradle-properties.outputs.DEPS_FABRIC_API }}
